#ifndef DEFINES_H
#define DEFINES_H

#define FPS 60

#define SCREENWIDTH 640
#define SCREENHEIGHT 480

#define MAPCOUNT 5

#define GRAVITY 0.5
#define GRAVITY_SPEED_MAX 10

#define MOVE_ACCELERATION 0.5
#define MOVE_DEACCELERATION 0.3
#define MOVE_MAX_SPEED 3.7
#define JUMP_FORCE 5
#define JUMP_MAX_HOLD 19

#define LASER_SPEED 7
#define LASERMAXLIFETIME 60
#define WEAPONCOOLDOWN 30

#define BOSS_PROJECTILE_SPEED 7
#define BOSS_PROJECTILE_MAXLIFETIME 60

#define DEATHTIME 180
#define INVULNERABILITYTIME 100

#define SCOREBADGUY 7000
#define SCORESLIME 2000
#define SCOREBOSS 100000
#define SCORECOIN 100
#define SCOREWEAPON 10000
#define SCOREAMMO 500
#define SCOREHEART 1000
#define SCOREKEY 3000
#define SCOREDOOR 5000

#define AMMOFROMWEAPON 5
#define AMMOFROMPACK 10

#define CAMERA_X_FOLLOW_RANGE 40
#define CAMERA_Y_FOLLOW_RANGE 60


#endif
